#!/bin/bash

operation=$1
tmuxinator_config=$2

if [ $operation == "start" ]
  then
  tmux has-session -t $tmuxinator_config 2> /dev/null

  if [ $? != 0 ]
  then
    tmuxinator start $tmuxinator_config $3
  else
    echo "tmux: $tmuxinator_config session is already running."
  fi
fi

if [ $operation == "stop" ]
  then
  tmux has-session -t $tmuxinator_config 2> /dev/null

  if [ $? == 0 ]
  then
    tmux send-keys -t $tmuxinator_config:$i.1 C-c C-m

    tmux kill-session -t $tmuxinator_config
  else
    echo "tmux: no $tmuxinator_config session found."
  fi
fi
